[package]
name = "omada_backup"
authors = ["Jacob Millward <jacob@millward.dev>"]
description = "A utility for downloading backups of a TP-Link Omada SDN Controller"
repository = "https://github.com/JacobMillward/omada_backup"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.14", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "cookies"] }
tokio = { version = "1", features = ["full"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
percent-encoding = "2.1.0"