name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            default: true

      - run: cargo build --release

      - name: Upload build artifact (Windows)
        uses: actions/upload-artifact@v3
        if: runner.os == 'Windows'
        with:
          name: omada-backup-${{ runner.os }}
          path: target/release/omada_backup.exe
      - name: Upload build artifact (Linux, OSX)
        uses: actions/upload-artifact@v3
        if: runner.os != 'Windows'
        with:
          name: omada-backup-${{ runner.os }}
          path: target/release/omada_backup