name: Create Release
permissions:
  contents: write
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      upload_artifacts: true
      release: true
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: release_artifacts

      - name: Rename artifacts
        working-directory: ./release_artifacts
        run: |
          for dir in *; do
            platform=$(echo ${dir#*--} | tr '[:upper:]' '[:lower:']);
            zip -r omada_backup-${{github.ref_name}}-$platform.zip $dir/*;
            rm -r $dir;
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release_artifacts/*
          fail_on_unmatched_files: true
          generate_release_notes: true